// api/security/approve.ts
// POST /api/security/approve
// Approves or rejects a remediation plan and creates a GitHub PR inline.

import type { VercelRequest, VercelResponse } from '@vercel/node';
import { initializeApp, getApps, cert } from 'firebase-admin/app';
import { getFirestore, FieldValue } from 'firebase-admin/firestore';
import { getAuth } from 'firebase-admin/auth';
import { Octokit } from '@octokit/rest';

const ALLOWED_ORIGINS = ['https://ops.bewatu.com', 'https://www.bewatu.com'];

function setCors(req: VercelRequest, res: VercelResponse) {
  const origin = req.headers.origin as string | undefined;
  const allowed = origin && ALLOWED_ORIGINS.includes(origin) ? origin : ALLOWED_ORIGINS[0];
  res.setHeader('Access-Control-Allow-Origin', allowed);
  res.setHeader('Access-Control-Allow-Methods', 'POST, OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type, Authorization');
}

function initAdmin() {
  if (!getApps().length) {
    const sa = process.env.FIREBASE_SERVICE_ACCOUNT;
    if (!sa) throw new Error('FIREBASE_SERVICE_ACCOUNT not set');
    initializeApp({ credential: cert(JSON.parse(sa)) });
  }
  return { db: getFirestore(), auth: getAuth() };
}

async function verifyOpsAgent(req: VercelRequest, db: ReturnType<typeof getFirestore>, auth: ReturnType<typeof getAuth>) {
  const authHeader = req.headers.authorization;
  if (!authHeader?.startsWith('Bearer ')) return null;
  try {
    const decoded = await auth.verifyIdToken(authHeader.slice(7));
    const opsDoc  = await db.collection('ops_staff').doc(decoded.uid).get();
    if (!opsDoc.exists) return null;
    return decoded;
  } catch { return null; }
}

function getGHRepo(repo: string): { owner: string; repo: string } {
  const map: Record<string, { owner: string; repo: string }> = {
    bewatu_v3:      { owner: 'bewatu8325', repo: 'BeWatu_V3' },
    bewatu_factory: { owner: 'bewatu8325', repo: 'bewatu-factory-main-3' },
    bewatu_ops:     { owner: 'bewatu8325', repo: 'bewatu-ops' },
    shared:         { owner: 'bewatu8325', repo: 'BeWatu_V3' },
  };
  return map[repo] || map.shared;
}

function buildPRBody(plan: any, finding: any, agentEmail: string): string {
  return `## Security Finding: ${finding.findingId}

**Severity:** ${finding.severity?.toUpperCase()}
**Risk Score:** ${finding.riskScore}/100
**Category:** ${finding.category?.replace(/_/g, ' ')}

### Summary
${plan.summary}

### Actions required
${(plan.actions || []).map((a: string) => `- ${a.replace(/_/g, ' ')}`).join('\n')}

### Affected assets
${(finding.affectedAssets || []).map((a: string) => `- \`${a}\``).join('\n') || '- none specified'}

### Rollback plan
${plan.rollbackPlan}

### Verification steps
${(plan.verificationSteps || []).map((s: string, i: number) => `${i + 1}. ${s}`).join('\n')}

${finding.aiExplanation ? `### Plain English\n${finding.aiExplanation}` : ''}

---
> Generated by BeWatu Security Platform
> Approved by: ${agentEmail}
> Finding: \`${finding.findingId}\`
`.trim();
}

async function createSecurityPR(
  plan: any,
  finding: any,
  agentEmail: string
): Promise<{ prUrl: string; prNumber: number } | null> {
  const githubToken = process.env.GITHUB_TOKEN;
  if (!githubToken) {
    console.error('GITHUB_TOKEN not set — cannot create PR');
    return null;
  }

  try {
    const octokit    = new Octokit({ auth: githubToken });
    const { owner, repo } = getGHRepo(finding.repo || 'shared');
    const branchName = `security/fix-${(finding.findingId || 'unknown').toLowerCase()}`;

    // Get main branch SHA
    const mainRef = await octokit.git.getRef({ owner, repo, ref: 'heads/main' });

    // Create security branch
    await octokit.git.createRef({
      owner, repo,
      ref: `refs/heads/${branchName}`,
      sha: mainRef.data.object.sha,
    }).catch(e => {
      // Branch may already exist — that's fine
      if (!e.message?.includes('already exists')) throw e;
    });

    // For non-automatable fixes, add an empty commit so GitHub allows PR creation
    const isAutomatable = plan.automatable === true;
    if (!isAutomatable) {
      try {
        // Get the tree SHA from main
        const mainCommit = await octokit.git.getCommit({
          owner, repo, commit_sha: mainRef.data.object.sha,
        });
        console.log('mainCommit tree:', mainCommit.data.tree.sha);

        // Create a blob with a placeholder file
        const blob = await octokit.git.createBlob({
          owner, repo,
          content: Buffer.from(`# Security Fix Tracking

Finding: ${finding.findingId}
Title: ${finding.title}
Approved: ${new Date().toISOString()}
`).toString('base64'),
          encoding: 'base64',
        });
        console.log('blob sha:', blob.data.sha);

        // Create a new tree with the placeholder file
        const newTree = await octokit.git.createTree({
          owner, repo,
          base_tree: mainCommit.data.tree.sha,
          tree: [{
            path:    '.security-fixes/tracking.md',
            mode:    '100644',
            type:    'blob',
            sha:     blob.data.sha,
          }],
        });
        console.log('newTree sha:', newTree.data.sha);

        // Create commit on the branch
        const newCommit = await octokit.git.createCommit({
          owner, repo,
          message: `[SECURITY] Track fix for ${finding.findingId}: ${finding.title}`,
          tree:    newTree.data.sha,
          parents: [mainRef.data.object.sha],
        });
        console.log('newCommit sha:', newCommit.data.sha);

        // Update branch ref to point to new commit
        await octokit.git.updateRef({
          owner, repo,
          ref:   `heads/${branchName}`,
          sha:   newCommit.data.sha,
          force: false,
        });
        console.log('Branch updated successfully');
      } catch (commitErr: any) {
        console.error('Empty commit creation failed:', commitErr.message);
        throw commitErr;
      }
    }

    // Create PR (draft for manual fixes, ready for automatable)
    const pr = await octokit.pulls.create({
      owner, repo,
      title: `[SECURITY] ${finding.severity?.toUpperCase() || 'MEDIUM'}: ${finding.title}`,
      head:  branchName,
      base:  'main',
      body:  buildPRBody(plan, finding, agentEmail),
      draft: !isAutomatable,
    });

    // Add labels
    const labels = ['security', finding.severity || 'medium'];
    await octokit.issues.addLabels({
      owner, repo,
      issue_number: pr.data.number,
      labels,
    }).catch(() => {}); // labels failing shouldn't block the PR

    console.log(`Created PR #${pr.data.number}: ${pr.data.html_url}`);
    return { prUrl: pr.data.html_url, prNumber: pr.data.number };
  } catch (e: any) {
    console.error('PR creation failed:', e.message);
    return null;
  }
}

export default async function handler(req: VercelRequest, res: VercelResponse) {
  setCors(req, res);
  if (req.method === 'OPTIONS') return res.status(200).end();
  if (req.method !== 'POST') return res.status(405).json({ error: 'Method not allowed' });

  try {
    const { db, auth } = initAdmin();
    const agent = await verifyOpsAgent(req, db, auth);
    if (!agent) return res.status(403).json({ error: 'Ops access required' });

    const { approvalId, decision, note } = req.body;
    if (!approvalId || !decision) return res.status(400).json({ error: 'approvalId and decision required' });
    if (!['approved', 'rejected'].includes(decision)) return res.status(400).json({ error: 'decision must be approved or rejected' });

    const approvalRef = db.collection('approval_requests').doc(approvalId);
    const approval    = await approvalRef.get();
    if (!approval.exists) return res.status(404).json({ error: 'Approval not found' });
    if (approval.data()!.status !== 'pending') return res.status(409).json({ error: 'Already decided' });

    const { findingId, remediationPlanId: planId } = approval.data()!;

    // Record decision
    await approvalRef.update({
      status:       decision,
      decisionBy:   agent.uid,
      decisionAt:   FieldValue.serverTimestamp(),
      decisionNote: note ?? null,
    });

    // Write audit entry
    await db.collection('audit_log').add({
      action:     `security_remediation_${decision}`,
      actorUid:   agent.uid,
      actorEmail: agent.email,
      approvalId, planId, findingId,
      note:       note ?? null,
      timestamp:  FieldValue.serverTimestamp(),
    });

    if (decision === 'approved') {
      // Update plan and finding status
      await db.collection('remediation_plans').doc(planId).update({
        status:     'executing',
        approvedBy: agent.uid,
        approvedAt: FieldValue.serverTimestamp(),
        executedAt: FieldValue.serverTimestamp(),
      });
      await db.collection('security_findings').doc(findingId).update({
        status:    'executing',
        updatedAt: FieldValue.serverTimestamp(),
      });

      // Get plan and finding data for PR creation
      const [planDoc, findingDoc] = await Promise.all([
        db.collection('remediation_plans').doc(planId).get(),
        db.collection('security_findings').doc(findingId).get(),
      ]);

      const plan    = planDoc.data()!;
      const finding = findingDoc.data()!;

      // Create GitHub PR inline
      const prResult = await createSecurityPR(plan, finding, agent.email || 'ops@bewatu.com');

      if (prResult) {
        await db.collection('remediation_plans').doc(planId).update({
          status:    'completed',
          prUrl:     prResult.prUrl,
          prNumber:  prResult.prNumber,
        });
        await db.collection('security_findings').doc(findingId).update({
          status:    'remediation_pending',
          updatedAt: FieldValue.serverTimestamp(),
        });
        return res.status(200).json({ approvalId, decision, planId, prUrl: prResult.prUrl, prNumber: prResult.prNumber });
      } else {
        // PR creation failed but approval was recorded — mark as approved manually
        await db.collection('remediation_plans').doc(planId).update({ status: 'approved' });
        await db.collection('security_findings').doc(findingId).update({
          status: 'remediation_pending', updatedAt: FieldValue.serverTimestamp(),
        });
        return res.status(200).json({ approvalId, decision, planId, warning: 'Approval recorded but PR creation failed — check GITHUB_TOKEN' });
      }

    } else {
      // Rejected
      await db.collection('remediation_plans').doc(planId).update({ status: 'failed' });
      await db.collection('security_findings').doc(findingId).update({
        status:               'accepted_risk',
        falsePositiveReason:  note || 'Rejected by ops agent',
        updatedAt:            FieldValue.serverTimestamp(),
      });
      return res.status(200).json({ approvalId, decision, planId });
    }

  } catch (err: any) {
    console.error('approve.ts error:', err);
    return res.status(500).json({ error: err.message || 'Internal error' });
  }
}
