// api/security/execute.ts
// POST /api/security/execute

import type { VercelRequest, VercelResponse } from '@vercel/node';
import { initializeApp, getApps, cert } from 'firebase-admin/app';
import { getFirestore, FieldValue } from 'firebase-admin/firestore';
import { Octokit } from '@octokit/rest';

function initAdmin() {
  if (!getApps().length) {
    const sa = process.env.FIREBASE_SERVICE_ACCOUNT;
    if (!sa) throw new Error('FIREBASE_SERVICE_ACCOUNT not set');
    initializeApp({ credential: cert(JSON.parse(sa)) });
  }
  return { db: getFirestore() };
}

function validateServiceToken(req: VercelRequest): boolean {
  const auth = req.headers.authorization;
  if (!auth?.startsWith('Bearer ')) return false;
  return auth.slice(7) === process.env.BEWATU_SECURITY_TOKEN;
}

function getGHRepo(repo: string): { owner: string; repo: string } {
  const map: Record<string, { owner: string; repo: string }> = {
    bewatu_v3:      { owner: 'bewatu', repo: 'BeWatu_V3' },
    bewatu_factory: { owner: 'bewatu', repo: 'bewatu-factory-main-3' },
    bewatu_ops:     { owner: 'bewatu', repo: 'bewatu-ops' },
    shared:         { owner: 'bewatu', repo: 'BeWatu_V3' },
  };
  return map[repo] || map.shared;
}

function buildPRBody(plan: any, finding: any): string {
  return `## Security Finding: ${finding.findingId}
**Severity:** ${finding.severity?.toUpperCase()}
**Risk Score:** ${finding.riskScore}/100

### Summary
${plan.summary}

### Rollback plan
${plan.rollbackPlan}

### Verification steps
${(plan.verificationSteps || []).map((s: string, i: number) => `${i+1}. ${s}`).join('\n')}

---
> Generated by BeWatu Security Platform
> Finding: \`${finding.findingId}\``.trim();
}

export default async function handler(req: VercelRequest, res: VercelResponse) {
  if (req.method !== 'POST') return res.status(405).json({ error: 'Method not allowed' });
  if (!validateServiceToken(req)) return res.status(403).json({ error: 'Unauthorised' });

  try {
    const { db } = initAdmin();
    const { planId, approvedBy } = req.body;
    if (!planId) return res.status(400).json({ error: 'planId required' });

    const planDoc = await db.collection('remediation_plans').doc(planId).get();
    if (!planDoc.exists) return res.status(404).json({ error: 'Plan not found' });
    const plan = planDoc.data()!;
    if (!plan.automatable) return res.status(400).json({ error: 'Plan is not automatable' });

    const findingDoc = await db.collection('security_findings').doc(plan.findingId).get();
    const finding    = findingDoc.data()!;

    await planDoc.ref.update({
      status: 'executing', approvedBy,
      approvedAt: FieldValue.serverTimestamp(),
      executedAt: FieldValue.serverTimestamp(),
    });

    const octokit    = new Octokit({ auth: process.env.GITHUB_TOKEN });
    const { owner, repo } = getGHRepo(finding.repo);
    const branchName = `security/fix-${finding.findingId?.toLowerCase()}`;

    const mainRef = await octokit.git.getRef({ owner, repo, ref: 'heads/main' });
    await octokit.git.createRef({
      owner, repo,
      ref: `refs/heads/${branchName}`,
      sha: mainRef.data.object.sha,
    });

    const pr = await octokit.pulls.create({
      owner, repo,
      title: `[SECURITY] ${finding.severity?.toUpperCase()}: ${finding.title}`,
      head: branchName, base: 'main',
      body: buildPRBody({ ...plan, id: planId }, finding),
      draft: false,
    });

    await octokit.issues.addLabels({
      owner, repo, issue_number: pr.data.number,
      labels: ['security', finding.severity || 'medium', 'requires-security-review'],
    });

    await planDoc.ref.update({
      status: 'completed', prUrl: pr.data.html_url, prNumber: pr.data.number,
    });

    await findingDoc.ref.update({
      status: 'remediation_pending', updatedAt: FieldValue.serverTimestamp(),
    });

    return res.status(200).json({ planId, prUrl: pr.data.html_url, prNumber: pr.data.number });

  } catch (err: any) {
    console.error('execute.ts error:', err);
    if (req.body?.planId) {
      try {
        const { db } = initAdmin();
        await db.collection('remediation_plans').doc(req.body.planId).update({ status: 'failed' });
      } catch {}
    }
    return res.status(500).json({ error: err.message || 'Internal error' });
  }
}
