// api/security/execute.ts
// POST /api/security/execute
// Executes an approved, automatable remediation plan.
// For automatable plans: creates a GitHub PR with the fix.
// For manual plans: this endpoint should not be called (approve.ts skips it).
//
// Body: { planId: string, approvedBy: string }

import type { VercelRequest, VercelResponse } from '@vercel/node';
import * as admin from 'firebase-admin';
import { Octokit } from '@octokit/rest';

if (!admin.apps.length) {
  admin.initializeApp({ credential: admin.credential.cert(
    JSON.parse(process.env.FIREBASE_SERVICE_ACCOUNT!)
  )});
}

const db = admin.firestore();

function validateServiceToken(req: VercelRequest): boolean {
  const auth = req.headers.authorization;
  if (!auth?.startsWith('Bearer ')) return false;
  return auth.slice(7) === process.env.BEWATU_SECURITY_TOKEN;
}

function getRepoForFinding(repo: string): { owner: string; repo: string } {
  const map: Record<string, { owner: string; repo: string }> = {
    bewatu_v3:      { owner: 'bewatu', repo: 'BeWatu_V3' },
    bewatu_factory: { owner: 'bewatu', repo: 'bewatu-factory-main-3' },
    bewatu_ops:     { owner: 'bewatu', repo: 'bewatu-ops' },
    shared:         { owner: 'bewatu', repo: 'BeWatu_V3' },
  };
  return map[repo] || map.shared;
}

function buildPRBody(plan: any, finding: any): string {
  return `## Security Finding: ${finding.findingId}

**Severity:** ${finding.severity?.toUpperCase()}
**Risk Score:** ${finding.riskScore}/100
**Category:** ${finding.category}

### Summary
${plan.summary}

### What this PR does
${(plan.actions as string[]).map(a => `- ${a.replace(/_/g, ' ')}`).join('\n')}

### Affected assets
${(finding.affectedAssets as string[]).map((a: string) => `- \`${a}\``).join('\n')}

### Rollback plan
${plan.rollbackPlan}

### Verification steps
${(plan.verificationSteps as string[]).map((s: string, i: number) => `${i + 1}. ${s}`).join('\n')}

---
> This PR was generated by the BeWatu Security Platform.
> Approved by: \`${plan.approvedBy}\`
> Finding ID: \`${finding.findingId}\`
> Approval: https://ops.bewatu.com/security/approvals/${plan.id}
`.trim();
}

async function applyDiffToBranch(
  octokit: Octokit,
  owner: string,
  repo: string,
  branch: string,
  diff: string,
  filePath: string
): Promise<void> {
  // Get current file content
  let currentContent = '';
  let currentSha     = '';

  try {
    const fileRes = await octokit.repos.getContent({ owner, repo, path: filePath, ref: branch });
    if ('content' in fileRes.data) {
      currentContent = Buffer.from(fileRes.data.content, 'base64').toString('utf-8');
      currentSha     = fileRes.data.sha;
    }
  } catch {
    // File doesn't exist yet — that's fine for new files
  }

  // Apply the unified diff (simplified — for production use the `diff` npm package)
  // This handles the simple CORS wildcard case from the plan
  const lines     = currentContent.split('\n');
  const diffLines = diff.split('\n');
  let modified    = currentContent;

  for (const dLine of diffLines) {
    if (dLine.startsWith('-  ') && !dLine.startsWith('---')) {
      const toRemove = dLine.slice(1).trim();
      modified = modified.replace(toRemove, '');
    }
  }

  const addLines = diffLines
    .filter(l => l.startsWith('+') && !l.startsWith('+++'))
    .map(l => l.slice(1))
    .join('\n');

  modified = modified + '\n' + addLines;

  await octokit.repos.createOrUpdateFileContents({
    owner,
    repo,
    path:    filePath,
    message: `[SECURITY] Apply automated fix`,
    content: Buffer.from(modified).toString('base64'),
    branch,
    ...(currentSha ? { sha: currentSha } : {}),
  });
}

export default async function handler(req: VercelRequest, res: VercelResponse) {
  if (req.method !== 'POST') return res.status(405).json({ error: 'Method not allowed' });
  if (!validateServiceToken(req)) return res.status(403).json({ error: 'Unauthorised' });

  const { planId, approvedBy } = req.body;
  if (!planId) return res.status(400).json({ error: 'planId required' });

  try {
    const planDoc = await db.collection('remediation_plans').doc(planId).get();
    if (!planDoc.exists) return res.status(404).json({ error: 'Plan not found' });

    const plan = planDoc.data()!;
    if (!plan.automatable) {
      return res.status(400).json({ error: 'Plan is not automatable — manual action required' });
    }

    const findingDoc = await db.collection('security_findings').doc(plan.findingId).get();
    const finding    = findingDoc.data()!;

    // Update plan status to executing
    await planDoc.ref.update({
      status:     'executing',
      approvedBy,
      approvedAt: admin.firestore.FieldValue.serverTimestamp(),
      executedAt: admin.firestore.FieldValue.serverTimestamp(),
    });

    const octokit = new Octokit({ auth: process.env.GITHUB_TOKEN });
    const { owner, repo } = getRepoForFinding(finding.repo);

    // Create branch
    const branchName = `security/fix-${finding.findingId.toLowerCase()}`;
    const mainRef    = await octokit.git.getRef({ owner, repo, ref: 'heads/main' });

    await octokit.git.createRef({
      owner, repo,
      ref: `refs/heads/${branchName}`,
      sha: mainRef.data.object.sha,
    });

    // Apply diff if present
    if (plan.diff && finding.evidence?.filePath) {
      await applyDiffToBranch(octokit, owner, repo, branchName, plan.diff, finding.evidence.filePath);
    }

    // Create PR
    const pr = await octokit.pulls.create({
      owner, repo,
      title: `[SECURITY] ${finding.severity?.toUpperCase()}: ${finding.title}`,
      head:  branchName,
      base:  'main',
      body:  buildPRBody({ ...plan, id: planId, approvedBy }, finding),
      draft: false,
    });

    // Add labels
    await octokit.issues.addLabels({
      owner, repo,
      issue_number: pr.data.number,
      labels: ['security', finding.severity, 'requires-security-review'],
    });

    // Save PR info to plan
    await planDoc.ref.update({
      status:    'completed',
      prUrl:     pr.data.html_url,
      prNumber:  pr.data.number,
    });

    // Update finding status
    await findingDoc.ref.update({
      status:    'remediation_pending',
      updatedAt: admin.firestore.FieldValue.serverTimestamp(),
    });

    // Trigger verification (async)
    setTimeout(async () => {
      await fetch(`${process.env.VERCEL_URL || 'https://www.bewatu.com'}/api/security/verify`, {
        method:  'POST',
        headers: {
          'Content-Type':  'application/json',
          'Authorization': `Bearer ${process.env.BEWATU_SECURITY_TOKEN}`,
        },
        body: JSON.stringify({ planId, prNumber: pr.data.number, repo: finding.repo }),
      });
    }, 1000);

    return res.status(200).json({ planId, prUrl: pr.data.html_url, prNumber: pr.data.number });

  } catch (err: any) {
    console.error('execute.ts error:', err);
    // Mark plan as failed
    if (planId) {
      await db.collection('remediation_plans').doc(planId).update({ status: 'failed' }).catch(() => {});
    }
    return res.status(500).json({ error: 'Internal error' });
  }
}
